name: Run Tests
on: push

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.6.7
          poetry_version: 1.0.9
          # working_directory: ./working_dir # Optional, defaults to '.'
          args: install
      - name: Run pytest
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.6.7
          poetry_version: 1.0.9
          # working_directory: ./working_dir
          args: run python -m pytest

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.6.7
          poetry_version: 1.0.9

      - name: Make Coverage
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.6.7
          poetry_version: 1.0.9
          # working_directory: ./working_dir
          args: coverage run -m pytest

      - name: HTML Coverage
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.6.7
          poetry_version: 1.0.9
          # working_directory: ./working_dir
          args: coverage report
      
      - name: HTML Coverage
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.6.7
          poetry_version: 1.0.9
          # working_directory: ./working_dir
          args: coverage html

      - uses: actions/upload-artifact@v2
        name: Upload Coverage
        with:
          name: html_coverage
          path: htmlcov

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.5.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: htmlcov  # The folder the action should deploy.