name: Run Tests
on:
  push:
    branches:
      - '*'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 13 * * 1-5'
# Add cron job to ensure external webpages + apis have no changed
jobs:
  run_tests:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.6.7
          poetry_version: 1.0.9
          args: install
      
      - name: Coverage Report
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.6.7
          poetry_version: 1.0.9
          # working_directory: ./working_dir
          args: run python -m pytest --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          fail_ci_if_error: true