name: Run Tests
on: push

jobs:
  run_tests:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.6.7
          poetry_version: 1.0.9
          args: install
      
      - name: Coverage Report
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.6.7
          poetry_version: 1.0.9
          # working_directory: ./working_dir
          args: run python -m pytest --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          fail_ci_if_error: true