name: Run Tests for python 3.6.9
on:
  push:
    branches:
      - '**'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 13 * * 1-5'
# Add cron job to ensure external webpages + apis have no changed
jobs:
  run_tests:
    strategy:
        fail-fast: false
        matrix:
          python-version: [3.6.7, 3.7, 3.8, 3.9]
          poetry-version: [1.1.2]
          os: [ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.os }}
    name: coverage
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install Dependencies
        run: poetry install

      - name: Dataclasses for python 3.6
        if: ${{ matrix.python-version }} == "3.6.7" 
        run: | 
          ver=$(python -V 2>&1 | sed 's/.* \([0-9]\).\([0-9]\).*/\1\2/')
          echo $ver
          if [ "$ver" -eq "36" ]; then
            poetry run python -m pip install dataclasses
          fi

      - name: Coverage Report
        run: poetry run python -m pytest --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          fail_ci_if_error: true
